name: Go

on:
  push:
    branches: 
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: Create mandatory .env
        run: echo "SECRET=supersecret" > .env

      - name: Start services
        run: make docker.recreate

      - name: Test
        run: go test -v ./...

      - name: Stop services
        run: make docker.stop

  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: Create mandatory .env
        run: echo "SECRET=supersecret" > .env

      - name: Start services
        run: make docker.recreate

      - name: Test
        run: go test -v ./...

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: owlint/maestro
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Stop services
        run: make docker.stop
